spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}_test
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  mvc:
    servlet:
      path: /api/v1

imgbb:
  api-key: ${IMGBB_APIKEY}
  url: https://api.imgbb.com/1/upload