spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beer_store_test
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  mvc:
    servlet:
      path: /api/v1